RMA.Web/ViewModels/Master/CourseSalesMasterVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using EZY.RMAS.Contract;
using RMA.Web.ViewModels.CourseDetail;

namespace RMA.Web.ViewModels.Master
{
    public class CourseSalesMasterVm
    {
        public CourseSalesMaster courseSalesMaster { get; set; }

        public IEnumerable<Country> countryList { get; set; }

        public IEnumerable<Course> courseList { get; set; }

        public IEnumerable<EduProduct> eduProductList { get; set; }

        public IEnumerable<MonthVm> monthList { get; set; }
    }
}

RMA.Web/Controllers/MasterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using EZY.RMAS.Contract;
using EZY.RMAS.BusinessFactory;

namespace RMA.Web.Controllers
{
    [WebSsnFilter]
    public class MasterController : BaseController
    {
        /* Product Category Start */
        [HttpGet]
        public ActionResult ProductCategoryList()
        {
            var productCategoryList = new ProductCategoryBO()
                        .GetList()
                        .ToList();
            return View(productCategoryList);
        }

        [HttpGet]
        public PartialViewResult ProductCategoryGroup(short? productCategory)
        {
            var lookupBO = new LookupBO();
            ViewBag.ProductCategoryList = lookupBO.GetList()
                                       .Where(x => x.LookupCategory == "CategoryGroup")
                                       .Select(x => new LookUpSelect
                                       {
                                           Value = x.LookupID,
                                           Text = x.LookupDescription
                                       }).ToList<LookUpSelect>();
            if (productCategory == null)
            {
                ViewBag.Title = "New Product Category";
                return PartialView("ProductCategory", new ProductCategoryMaster());
            }
            else
            {
                ViewBag.Title = "Update Product Category";
                return PartialView("ProductCategory", new ProductCategoryBO()
                                        .GetList()
                                        .Where(x => x.ProductCategory == productCategory)
                                        .FirstOrDefault());

            }
        }
        [HttpPost]
        public ActionResult ProductCategory(ProductCategoryMaster productCategoryMaster)
        {
            //productCategoryMaster.LookupCategory = UTILITY.CONFIG_LOOKUPCATEGORY_PRODUCTCATEGORY;
            var lookUpBO = new ProductCategoryBO();
            var result = lookUpBO.SaveProduct(productCategoryMaster);

            return RedirectToAction("ProductCategoryList");
        }
        /*  Product Category End */

        /* Category Group Start */
        [HttpGet]
        public ActionResult CategoryList()
        {
            var CategoryList = new LookupBO()
                        .GetList()
                        .Where(x => x.LookupCategory == UTILITY.CONFIG_LOOKUPCATEGORY_CATEGORY)
                        .ToList();

            return View(CategoryList);
        }

        public PartialViewResult CategoryGroup(short? lookupID)
        {
            if (lookupID == null)
            {
                ViewBag.Title = "New Category Group";
                return PartialView(new Lookup());
            }
            else
            {
                ViewBag.Title = "Update Category Group";
                return PartialView(new LookupBO()
                                        .GetList()
                                        .Where(x => x.LookupID == lookupID)
                                        .FirstOrDefault());

            }
        }
        [HttpPost]
        public ActionResult SaveCategoryGroup(Lookup lookUp)
        {
            lookUp.LookupCategory = UTILITY.CONFIG_LOOKUPCATEGORY_CATEGORY;
            lookUp.Status = true;
            lookUp.ISOCode = "";
            lookUp.MappingCode = "";
            lookUp.CreatedBy = USER_ID;
            lookUp.CreatedOn = UTILITY.SINGAPORETIME;
            lookUp.ModifiedBy = USER_ID;
            lookUp.ModifiedOn = UTILITY.SINGAPORETIME;

            var lookUpBO = new LookupBO();
            var result = lookUpBO.SaveLookup(lookUp);

            return RedirectToAction("CategoryList");
        }
        [HttpPost]
        public JsonResult SaveCategory(string ProductCategory)
        {
            Lookup lookUp = new Lookup();
            lookUp.LookupCategory = UTILITY.CONFIG_LOOKUPCATEGORY_CATEGORY;
            lookUp.Status = true;
            lookUp.ISOCode = "";
            lookUp.MappingCode = "";
            lookUp.CreatedBy = USER_ID;
            lookUp.CreatedOn = UTILITY.SINGAPORETIME;
            lookUp.ModifiedBy = USER_ID;
            lookUp.ModifiedOn = UTILITY.SINGAPORETIME;
            lookUp.LookupDescription = "Desc";
            lookUp.LookupCode = ProductCategory;
            var lookUpBO = new LookupBO();
            var result = lookUpBO.SaveLookup(lookUp);
            ViewBag.ProductCategoryList = lookUpBO.GetList()
                                    .Where(x => x.LookupCategory == "CategoryGroup")
                                    .Select(x => new LookUpSelect
                                    {
                                        Value = x.LookupID,
                                        Text = x.LookupCode
                                    }).ToList<LookUpSelect>();
            return Json(ViewBag.ProductCategoryList, JsonRequestBehavior.AllowGet);
        }
        /* Category Group End */

        /* Currency Start */
        [HttpGet]
        public ActionResult CurrencyList()
        {
            var currencyCategoryList = new LookupBO()
                        .GetList()
                        .Where(x => x.LookupCategory == UTILITY.CONFIG_LOOKUPCATEGORY_CURRENCY)
                        .ToList();

            return View(currencyCategoryList);
        }

        public PartialViewResult Currency(short? lookupID)
        {
            if (lookupID == null)
            {
                ViewBag.Title = "New Currency";
                return PartialView(new Lookup());
            }
            else
            {
                ViewBag.Title = "Update Currency";
                return PartialView(new LookupBO()
                                        .GetList()
                                        .Where(x => x.LookupID == lookupID)
                                        .FirstOrDefault());

            }
        }

        [HttpPost]
        public ActionResult Currency(Lookup lookUp)
        {
            lookUp.LookupCategory = UTILITY.CONFIG_LOOKUPCATEGORY_CURRENCY;
            lookUp.Status = true;
            lookUp.ISOCode = "";
            lookUp.MappingCode = "";
            lookUp.CreatedBy = USER_ID;
            lookUp.CreatedOn = UTILITY.SINGAPORETIME;
            lookUp.ModifiedBy = USER_ID;
            lookUp.ModifiedOn = UTILITY.SINGAPORETIME;

            var lookUpBO = new LookupBO();
            var result = lookUpBO.SaveLookup(lookUp);

            return RedirectToAction("CurrencyList");
        }
        /* Currency End */

        [HttpGet]
        public ActionResult Products()
        {
            return View("Products", new List<Product>());
        }

        public PartialViewResult Product(string productCode = "", string modelNo = "")
        {
            var lookupBO = new LookupBO();
            ViewBag.ProductCategoryList = lookupBO.GetList()
                                    .Where(x => x.LookupCategory == "CategoryGroup")
                                    .Select(x => new LookUpSelect
                                    {
                                        Value = x.LookupID,
                                        Text = x.LookupCode
                                    }).ToList<LookUpSelect>();
            if (string.IsNullOrWhiteSpace(productCode))
            {

                ViewBag.Title = "New Product";
                return PartialView(new Product { Status = true });
            }
            else
            {
                ViewBag.Title = "Update Product";
                return PartialView(new ProductBO().GetProduct(new Product { ProductCode = productCode, ModelNo = modelNo }));

            }
        }

        [HttpPost]
        public ActionResult Product(Product product)
        {
            var productBO = new ProductBO();

            product.ProductCode = product.ModelNo;
            product.CreatedBy = USER_ID;
            product.CreatedOn = UTILITY.SINGAPORETIME;
            product.ModifiedBy = USER_ID;
            product.ModifiedOn = UTILITY.SINGAPORETIME;
            var result = productBO.SaveProduct(product);

            return RedirectToAction("Products");
        }

        [HttpPost]
        public ActionResult DeleteProduct(string productCode, string modelNo)
        {
            var productBO = new ProductBO();
            var result = productBO.DeleteProduct(new Product { ProductCode = productCode, ModelNo = modelNo });
            return View("Products", productBO.GetList());
        }

        [HttpPost]
        public JsonResult GetProducts(DataTableObject Obj)
        {
            var products = new ProductBO().GetProductTableDataList(Obj);
            var totalRecords = new ProductBO().GetList().Count();

            return Json(new { products = products, totalRecords = totalRecords }, JsonRequestBehavior.AllowGet);
        }
    }
}

RMA.Web/Views/Master/CategoryList.cshtml
@model List<EZY.RMAS.Contract.Lookup>
@{
    ViewBag.Title = "CategoryList";
}
@section seccss{
    <link href="@Url.Content("~/Css/dataTables.bootstrap.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Css/dataTables.responsive.css")" rel="stylesheet" />
}
<section class="content">
    <div class="box box-dnex">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-product-hunt" aria-hidden="true"></i>&nbsp;Category Group</h3>
            <div class="box-tools">
                <button class="btn btn-default btn-sm" type="button" onclick="AddProductCategory()"><i class="fa fa-plus"></i>&nbsp;Add New Category Group</button>
            </div>
        </div>
        <div class="box-body">
            <div class="row" style="margin-top:10px;">
                <div class="col-md-8">
                    <table class="table table-striped" id="tblProducts">
                        <thead>
                            <tr>
                                <th>Product Code</th>
                                <th>Description</th>
                                <th>#Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @for (var i = 0; i < Model.Count; i++)
                            {
                                <tr>
                                    <td>@Model[i].LookupCode</td>
                                    <td>@Model[i].LookupDescription</td>
                                    <td>
                                        <button class="btn btn-primary btn-sm" onclick="EditProductCategory(@Model[i].LookupID)"><i class="fa fa-pencil-square-o"></i>&nbsp;Edit</button>
                                        @*<button class="btn btn-danger btn-sm" onclick="DeleteProductCategory(@Model[i].LookupID)"><i class="fa fa-trash-o"></i>&nbsp;Delete</button>*@
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
        <div class="box-footer">
            <div class="row">
            </div>
        </div>
    </div>
</section>
@using (Html.BeginForm("SaveCategoryGroup", "Master", FormMethod.Post, new { id = "frmProductCategory", name = "frmProductCategory" }))
{
    <div id="ProductCategoryModal" class="modal fade" role="dialog">
    </div>
}
@section secscripts{
    <script type="text/javascript">
        function AddProductCategory() {
            $.ajax({
                url: '@Url.Content("~/Master/CategoryGroup")',
                method: 'get',
                contentType: 'text/html',
                success: function (html) {

                    $('#ProductCategoryModal').html(html);
                    $('#ProductCategoryModal').modal('show');
                },
                error: function (err) {

                }
            });
        }

        $('#frmProductCategory').validate({
            rules: {
                LookupCode: {
                    required: true
                },
                LookupDescription: {
                    required: true
                }
            }
        });

        function EditProductCategory(lookupID) {
            $.ajax({
                url: '@Url.Content("~/Master/ProductCategory?lookupID=")' + lookupID,
                method: 'get',
                contentType: 'text/html',
                success: function (html) {
                    $('#ProductCategoryModal').html(html);
                    $('#ProductCategoryModal').modal('show');
                },
                error: function (err) {

                }
            });
        }

        function SaveCategoryGroup() {


            if ($('#frmProductCategory').valid()) {
                $('#frmProductCategory').submit();
            }
        };

        function DeleteProductCategory(lookupID) {

        }
    </script>
}

RMA.Web/Views/Master/CourseList.cshtml
@model IEnumerable<EZY.RMAS.Contract.CourseVm>
@{
    ViewBag.Title = "CourseList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section seccss{
    <link href="@Url.Content("~/Css/dataTables.bootstrap.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Css/dataTables.responsive.css")" rel="stylesheet" />
}

<section class="content">
    <div class="box box-dnex">
        <div class="box-header with-border">
            <div class="row">
                <section class="content-header">
                    <ol class="breadcrumb">
                        <li><a href='@Url.Content("~/Home/Index")'><i class="fa fa-dashboard"></i> Home</a></li>
                        <li><a href='@Url.Content("~/Home/education")'> Master Data</a></li>
                        <li class="active">Courses</li>
                    </ol>
                </section>
            </div>
            <div class="box-tools">
                <button class="btn btn-default btn-sm" type="button" onclick="AddCourse()"><i class="fa fa-plus"></i>&nbsp;Add New Course</button>
            </div>
        </div>
        <div class="box-body">
            <div class="row" style="margin-top:10px;">
                <div class="col-md-12">
                    <table class="table table-striped" id="tblProducts">
                        <thead>
                            <tr>
                                <th>Product</th>
                                <th>Course Name</th> 
                                <th>No Of Days</th>
                                <th>Country</th>
                                <th>Available Seats</th>
                                <th>Public Price</th>
                                <th>Private Price</th>
                                <th>#Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @for (var i = 0; i < Model.Count(); i++)
                            {
                                <tr>
                                    <td>@Model.ElementAt(i).ProductName</td>
                                    <td>@Model.ElementAt(i).CourseName</td>                                    
                                    <td>@Model.ElementAt(i).NoOfDays</td>
                                    <td>@Model.ElementAt(i).CountryName</td>
                                    <td>@Model.ElementAt(i).AvailableSeats</td>
                                    <td>@Model.ElementAt(i).PublicPrice</td>
                                    <td>@Model.ElementAt(i).PrivatePrice</td>
                                    <td>
                                        <button class="btn btn-primary btn-sm" onclick="EditCourse(@Model.ElementAt(i).Id)"><i class="fa fa-pencil-square-o"></i>&nbsp;Edit</button>
                                        @*<button class="btn btn-danger btn-sm" onclick="DeleteProductCategory(@Model[i].LookupID)"><i class="fa fa-trash-o"></i>&nbsp;Delete</button>*@
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="box-footer">
            <div class="row">
                <div class="col-md-12">
                    <button class="btn btn-default btn-sm pull-right" type="button" onclick="location.href = '@Url.Content("~/Home/Education")'"><i class="fa fa-backward"></i>&nbsp;Back</button>
                </div>

            </div>
        </div>
    </div>
</section>
@using (Html.BeginForm("SaveCourse", "Master", FormMethod.Post, new { id = "frmCourse", name = "frmCourse" }))
{
    <div id="CourseModal" class="modal fade" role="dialog">
    </div>
}
@section secscripts{
    <script type="text/javascript">
        function AddCourse() {
            $.ajax({
                url: '@Url.Content("~/Master/Course")',
                method: 'get',
                contentType: 'text/html',
                success: function (html) {
                    $('#CourseModal').html(html).modal('show');
                },
                error: function (err) {

                }
            });
        }

        function EditCourse(Id) {            
            $.ajax({
                url: '@Url.Content("~/Master/Course?Id=")' + Id,
                method: 'get',
                contentType: 'text/html',
                success: function (html) {
                    $('#CourseModal').html(html).modal('show');
                },
                error: function (err) {

                }
            });
        }

        $('#frmCourse').validate({
            rules: {
                Country: {
                    required: true
                },
                Product: {
                    required: true
                },
                CourseName: {
                    required: true,
                    maxlength: 50
                },
                CourseDescription: {
                    required: true,
                    maxlength: 255
                },
                NoOfDays: {
                    required: true,
                    maxlength:  4
                },
                PublicPrice: {
                    required: true
                },
                PrivatePrice: {
                    required: true
                }
            }
        });

        function SaveCourse() {
            if ($('#frmCourse').valid()) {
                $('#frmCourse').submit();
            }
        };        
    </script>
}

RMA.Web/Views/Master/EduProductList.cshtml
@model IEnumerable<EZY.RMAS.Contract.EduProduct>
@{
    ViewBag.Title = "EduProductList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section seccss{
    <link href="@Url.Content("~/Css/dataTables.bootstrap.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Css/dataTables.responsive.css")" rel="stylesheet" />
}

<section class="content">
    <div class="box box-dnex">
        <div class="box-header with-border">
            <div class="row">
                <section class="content-header">
                    <ol class="breadcrumb">
                        <li><a href='@Url.Content("~/Home/Index")'><i class="fa fa-dashboard"></i> Home</a></li>
                        <li><a href='@Url.Content("~/Home/education")'> Master Data</a></li>
                        <li class="active">Education Product</li>
                    </ol>
                </section>
            </div>
            <div class="box-tools">
                <button class="btn btn-default btn-sm" type="button" onclick="AddEduProduct()"><i class="fa fa-plus"></i>&nbsp;Add New Product</button>
            </div>
        </div>
        <div class="box-body">
            <div class="row" style="margin-top:10px;">
                <div class="col-md-8">
                    <table class="table table-striped" id="tblProducts">
                        <thead>
                            <tr>
                                <th>Product Name</th>                                
                                <th>#Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @for (var i = 0; i < Model.Count(); i++)
                            {
                                <tr>
                                    <td>@Model.ElementAt(i).ProductName</td>                                    
                                    <td>
                                        <button class="btn btn-primary btn-sm" onclick="EditEduProduct(@Model.ElementAt(i).Id)"><i class="fa fa-pencil-square-o"></i>&nbsp;Edit</button>
                                        @*<button class="btn btn-danger btn-sm" onclick="DeleteProductCategory(@Model[i].LookupID)"><i class="fa fa-trash-o"></i>&nbsp;Delete</button>*@
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="box-footer">
            <div class="row">
                <div class="col-md-12">
                    <button class="btn btn-default btn-sm pull-right" type="button" onclick="location.href = '@Url.Content("~/Home/Education")'"><i class="fa fa-backward"></i>&nbsp;Back</button>
                </div>

            </div>
        </div>
    </div>
</section>
@using (Html.BeginForm("SaveEduProduct", "Master", FormMethod.Post, new { id = "frmEduProduct", name = "frmEduProduct" }))
{
    <div id="EduProductModal" class="modal fade" role="dialog">
    </div>
}
@section secscripts{
    <script type="text/javascript">
        function AddEduProduct() {
            
            $.ajax({
                url: '@Url.Content("~/Master/EduProduct")',
                method: 'get',
                contentType: 'text/html',
                success: function (html) {

                    $('#EduProductModal').html(html);
                    $('#EduProductModal').modal('show');
                },
                error: function (err) {

                }
            });
        }

        function EditEduProduct(Id) {
            
            $.ajax({
                url: '@Url.Content("~/Master/EduProduct?Id=")' + Id,
                method: 'get',
                contentType: 'text/html',
                success: function (html) {
                    $('#EduProductModal').html(html);
                    $('#EduProductModal').modal('show');
                },
                error: function (err) {

                }
            });
        }

        $('#frmEduProduct').validate({
            rules: {
                ProductName: {
                    required: true,
                    maxlength: 50
                },
                ProductDescription: {
                    required: true,
                    maxlength: 255
                }
            }
        });

        function SaveEduProduct() {
            if ($('#frmEduProduct').valid()) {
                $('#frmEduProduct').submit();
            }
        };

        //$('#ProductCode').keypress(function (e) {
        //    if (e.which === 32)
        //        return false;
        //})​​​​​;
    </script>
}

RMA.Web/Views/Master/Product.cshtml
@model EZY.RMAS.Contract.Product
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">@ViewBag.Title</h4>
        </div>
        <div class="modal-body" id="ProductModalBody">
            <div class="row" style="margin-bottom:10px;">
                <div class="col-md-3">
                    <label class="control-label pull-right">Product Category</label>
                </div>
                <div class="col-md-5">
                    @Html.DropDownListFor(x => x.ProductCategory,
                            new SelectList(ViewBag.ProductCategoryList, "Value", "Text"),
                            "Select Product Category",
                            new { @class = "form-control input-sm"})
                </div>
                <div>
                    <button type="button" onclick="AddProduct()" class="btn btn-sm btn btn-success ref">
                        <i class="fa fa-refresh" aria-hidden="true"></i>
                    </button>
                    <button type="button" onclick="AddProductCategory()" class="btn btn-sm btn btn-primary">
                        <i class="fa fa-floppy-o"></i>&nbsp;Add
                    </button>
                </div>
                @*<div class="col-md-3">
                <button type="button" onclick="AddProductCategory()" class="btn btn-sm btn btn-primary">
                    <i class="fa fa-floppy-o"></i>&nbsp;Add
                </button>
            </div>*@
                </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col-md-3 col-md-offset-3 lookup">
                    @*@using (Html.BeginForm("SaveCategoryGroup", "Master", FormMethod.Post, new { id = "frm", name = "frm", enctype = "multipart/form-data" }))
                    {*@
                        @Html.TextBoxFor(x => x.ProductCategoryDescription,
            new { @class = "form-control input-sm", placeholder = "Lookup Code" })
                    @*}*@
                </div>
                &nbsp;
                <div class="col-md-1">
                    <button type="button" class="btn btn-sm btn btn-success lookup" onclick="SaveCategoryGroup()">
                        <i class="fa fa-floppy-o"></i>&nbsp;Update
                    </button>
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;display:none">
                <div class="col-md-3">
                    <label class="control-label pull-right">Product Code</label>
                </div>
                <div class="col-md-8">

                @Html.TextBoxFor(x => x.ProductCode, new { @class = "form-control input-sm", placeholder = "Product Code" })

                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col-md-3">
                    <label class="control-label pull-right">
                        Model No
                    </label>
                </div>
                <div class="col-md-6">
                    @Html.TextBoxFor(x => x.ModelNo, new { @class = "form-control input-sm", placeholder = "Model No" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label class="control-label pull-right">
                        Product Description
                    </label>
                </div>
                <div class="col-md-6">
                    @Html.TextAreaFor(x => x.Description, new { @class = "form-control input-sm", placeholder = "Product Description" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label class="control-label pull-right">
                        Is Active
                    </label>
                </div>
                <div class="col-md-6">
                    @Html.CheckBoxFor(x => x.Status)
                </div>
            </div>
        </div>
        <div class="modal-footer">
            @Html.Button("<i class='fa fa-floppy-o'></i>&nbsp;Save",
                 new { @class = "btn btn-danger btn-frmt green btn-sm", onclick = "SaveProduct()" },
                 SECURABLE.MASTER_ACTION_SAVEPRODUCT)
            <button type="reset" class="btn btn-default btn-frmt btn-sm" data-dismiss="modal">
                <i class="fa fa-times"></i>Cancel
            </button>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(function () {
        
        $('.lookup').hide();
        $('.ref').hide();
            //$('#frmAddProductCode').validate({
            //    rules: {
            //        LkpCode: {
            //            required: true
            //        }
            //    }
            //});
        });
        function AddProductCategory()
        {
            $('.lookup').show();
        }

        function SaveCategoryGroup()
        {
            var Category = $('#ProductCategoryDescription').val();

            if (Category == "" || Category == undefined) {
                alert("Please Enter Lookup Code!");
                return false;
            }

            if (confirm("Are you sure ? You want to save \nDescription: " + $('#ProductCategoryDescription').val()))
            {
                
                $.ajax({
                    url: '@Url.Content("~/Master/SaveCategory?ProductCategory=")' + Category,
                    method: 'POST',
                    contentType: 'application/json',
                    success: function (data) {
                        //$.each(data, function (i, item) {
                            
                            alert("Product Category is added!");
                            $('.ref').show();
                             //$('#ProductCategory').append('<option value="' + i.Value + '">' + item.Text + '</option>');
                            $('.lookup').hide();
                        //});                     
                    },
                    error: function (err) {
                        

                    }
                });
            }
        }
    </script>