RMA.Web/ViewModels/Report/ReportMenu.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RMA.Web.ViewModels.Report
{
    public class ReportMenu
    {
        public int MenuID { get; set; }
        public string MenuName { get; set; }
        public string NavURL { get; set; }

    }
}

RMA.Web/Controllers/ReportsController.cs
using EZY.RMAS.BusinessFactory;
using EZY.RMAS.Contract;
using RMA.Web;
using RMA.Web.ViewModels.Report;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;


namespace RMA.Web.Reports.Controllers
{

    [WebSsnFilter]
    public class ReportsController : BaseController
    {
        public static string REPORTSUBFOLDER = WebConfigurationManager.AppSettings["ReportPath"].ToString();

        //string url = "MaterialInwardSSRSReport";
        //NetworkCredential nwc = new NetworkCredential("ragsarma-001", "n0ki@3310", "ifc");
        //WebClient client = new WebClient();
        //client.Credentials = nwc;
        //string reportURL = string.Format("{0}?{1}{2}&rs:Command=Render&rs:Format=PDF&rc:Toolbar=false&rc:Parameters=false&BranchID={3}&DateFrom={4}&DateTo={5}", "http://sql5002.smarterasp.net/ReportServer",
        //    "/ragsarma-001/RMAReports/", url, branchID, dateFrom, dateTo);
        //var cd = new System.Net.Mime.ContentDisposition
        //{
        //    FileName = "Report.pdf",
        //    Inline = false,
        //};
        //Response.AppendHeader("Content-Disposition", cd.ToString());
        //return File(client.DownloadData(reportURL), "application/pdf");
        public ActionResult MaterialInwardProductQtyMonthWise(ReportParams reportParams)
        {

            ViewBag.ReportMenuList = GetReportMenu();
            reportParams.BranchID = BRANCH_ID;
            reportParams.DateFrom = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1).AddMonths(-1);
            reportParams.DateTo = DateTime.Now.Date;
            reportParams.Year = Convert.ToInt16(DateTime.Now.Year);
            reportParams.ProductCode = 0;
            var YearList = new List<Year>();
            var Year = new DashBoardBO().GetRMAOutwardYear().Select(x => new Year() { Value = x.Year, Text = x.Year }).FirstOrDefault();
            YearList.Add(Year);
            if (new DashBoardBO().GetRMAOutwardYear().Any(x => x.Year != Convert.ToInt16(DateTime.Now.Year)))
            {
                YearList.Add(new Year { Value = Convert.ToInt16(DateTime.Now.Year), Text = Convert.ToInt16(DateTime.Now.Year) });
            }
            ViewBag.Year = YearList;
            ViewBag.Branches = new BranchBO().GetList().Select(x => new { Value = x.BranchID, Text = x.BranchName });
            var ProductCategory = new LookupBO()
                                       .GetList()
                                       .Where(x => x.LookupCategory == "CategoryGroup" && x.Status == true)
                                       .Select(x => new SelectListItem
                                       {
                                           Value = x.LookupID.ToString(),
                                           Text = x.LookupCode
                                       })
                                       .ToList();
            ProductCategory.Add(new SelectListItem
            {
                Text = "ALL",
                Value = 0.ToString()
            });
            ViewBag.productCategory = ProductCategory;
            ViewBag.Login = BRANCH_ID;
            return View("MaterialInwardProductQty", reportParams);
        }

        private List<ReportMenu> GetReportMenu()
        {
            List<ReportMenu> all = new List<ReportMenu>();
            all.Add(new ReportMenu { MenuID = 1, MenuName = "Material Inward Product Qty", NavURL = "MaterialInwardProductQty" });
            all.Add(new ReportMenu { MenuID = 2, MenuName = "Material Inward Product Cost", NavURL = "MaterialInwardProductCost" });
            all.Add(new ReportMenu { MenuID = 3, MenuName = "Material Inward Total Invoice", NavURL = "MaterialInwardTotalInvoice" });
            all.Add(new ReportMenu { MenuID = 4, MenuName = "Material Outward Product Qty", NavURL = "MaterialOutwardProductQty" });
            all.Add(new ReportMenu { MenuID = 5, MenuName = "Material Outward Product Cost", NavURL = "MaterialOutwardProductCost" });
            all.Add(new ReportMenu { MenuID = 6, MenuName = "Material Outward Total Invoice", NavURL = "MaterialOutwardTotalInvoice" });
            all.Add(new ReportMenu { MenuID = 7, MenuName = "RMA Transaction Received", NavURL = "RMATransactionReceived" });
            all.Add(new ReportMenu { MenuID = 8, MenuName = "RMA Transaction Return", NavURL = "RMATransactionReturn" });
            all.Add(new ReportMenu { MenuID = 9, MenuName = "Products Category RMA Receipt Qty", NavURL = "ProductsCategoryRMAReceiptQty" });
            all.Add(new ReportMenu { MenuID = 10, MenuName = "Products Category RMA Receipt Value", NavURL = "ProductsCategoryRMAReceiptValue" });
            all.Add(new ReportMenu { MenuID = 11, MenuName = "RMA Receipt Quantity", NavURL = "RMAReceiptQuantity" });
            all.Add(new ReportMenu { MenuID = 12, MenuName = "RMA Receipt Value", NavURL = "RMAReceiptValue" });
            all.Add(new ReportMenu { MenuID = 13, MenuName = "RMA CreditNote ProductCategory", NavURL = "RMACreditNoteProductCategory" });
            all.Add(new ReportMenu { MenuID = 14, MenuName = "RMA CreditNote Value", NavURL = "RMACreditNoteValue" });
            return all;
        }

        public PartialViewResult ViewMaterialInwardProductQtyMonthWise(int? BranchID, string dateFrom, string dateTo, int? Year, int? ProductCode, string URL)
        {
            ViewBag.Title = "Material Inward Product Qty";
            ViewBag.BranchID = BranchID;
            ViewBag.Year = Year;
            ViewBag.DateFrom = dateFrom;
            ViewBag.DateTo = dateTo;
            ViewBag.ProductCode = ProductCode;
            ViewBag.ReportSource = "MaterialInwardProductQty";
            ViewBag.Url = string.Format("{0}{1}", REPORTSUBFOLDER, URL);
            return PartialView("ViewReport");
        }
        public ActionResult MaterialInwardProductCostMonthWise(ReportParams reportParams)
        {
            ViewBag.ReportMenuList = GetReportMenu();
            reportParams.BranchID = BRANCH_ID;
            reportParams.DateFrom = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1).AddMonths(-1);
            reportParams.DateTo = DateTime.Now.Date;
            reportParams.Year = Convert.ToInt16(DateTime.Now.Year);
            reportParams.ProductCode = 0;
            var YearList = new List<Year>();
            var Year = new DashBoardBO().GetRMAOutwardYear().Select(x => new Year() { Value = x.Year, Text = x.Year }).FirstOrDefault();
            YearList.Add(Year);
            if (new DashBoardBO().GetRMAOutwardYear().Any(x => x.Year != Convert.ToInt16(DateTime.Now.Year)))
            {
                YearList.Add(new Year { Value = Convert.ToInt16(DateTime.Now.Year), Text = Convert.ToInt16(DateTime.Now.Year) });
            }
            ViewBag.Year = YearList;
            ViewBag.Branches = new BranchBO().GetList().Select(x => new { Value = x.BranchID, Text = x.BranchName });
            var ProductCategory = new LookupBO()
                                       .GetList()
                                       .Where(x => x.LookupCategory == "CategoryGroup" && x.Status == true)
                                       .Select(x => new SelectListItem
                                       {
                                           Value = x.LookupID.ToString(),
                                           Text = x.LookupCode
                                       })
                                       .ToList();
            ProductCategory.Add(new SelectListItem
            {
                Text = "ALL",
                Value = 0.ToString()
            });
            ViewBag.productCategory = ProductCategory;
            ViewBag.Login = BRANCH_ID;
            return View("MaterialInwardProductCost", reportParams);
        }
        public ActionResult ViewMaterialInwardProductCostMonthWise(int? BranchID, string dateFrom, string dateTo, int? Year, int? ProductCode, string URL)
        {
            ViewBag.Title = "Material Inward Product Cost Report";
            ViewBag.BranchID = BranchID;
            ViewBag.Year = Year;
            ViewBag.DateFrom = dateFrom;
            ViewBag.DateTo = dateTo;
            ViewBag.ProductCode = ProductCode;
            ViewBag.ReportSource = "MaterialInwardProductCost";
            ViewBag.Url = string.Format("{0}{1}", REPORTSUBFOLDER, URL);
            //var path = "~/Views/Shared/_ReportViewerPartial.cshtml";
            return PartialView("ViewReport");
        }
        public ActionResult MaterialInwardTotalInvoicesProductMonthWise(ReportParams reportParams)
        {
            ViewBag.ReportMenuList = GetReportMenu();
            reportParams.BranchID = BRANCH_ID;
            reportParams.DateFrom = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1).AddMonths(-1);
            reportParams.DateTo = DateTime.Now.Date;
            reportParams.Year = Convert.ToInt16(DateTime.Now.Year);
            reportParams.ProductCode = 0;
            var YearList = new List<Year>();
            var Year = new DashBoardBO().GetRMAOutwardYear().Select(x => new Year() { Value = x.Year, Text = x.Year }).FirstOrDefault();
            YearList.Add(Year);
            if (new DashBoardBO().GetRMAOutwardYear().Any(x => x.Year != Convert.ToInt16(DateTime.Now.Year)))
            {
                YearList.Add(new Year { Value = Convert.ToInt16(DateTime.Now.Year), Text = Convert.ToInt16(DateTime.Now.Year) });
            }
            ViewBag.Year = YearList;
            ViewBag.Branches = new BranchBO().GetList().Select(x => new { Value = x.BranchID, Text = x.BranchName });
            var ProductCategory = new LookupBO()
                                       .GetList()
                                       .Where(x => x.LookupCategory == "CategoryGroup" && x.Status == true)
                                       .Select(x => new SelectListItem

RMA.Web/Views/Reports/CreditNoteProductCategory.cshtml
@model EZY.RMAS.Contract.RMACreditNoteDTO
@{
    ViewBag.Title = "CreditNoteProductCategory";
}
<link href="@Url.Content("~/Css/datepicker3.css")" rel="stylesheet" />
<link href="@Url.Content("~/Css/select2.min.css")" rel="stylesheet" />

<div id="myModal" class="modal fade" role="dialog" data-backdrop="static" data-keyboard="false">
</div>

<div id="loader"></div>
<section class="content">
    <div class="box box-dnex">
        <div class="box-header with-border">
            <div class="row">
                <section class="content-header">
                    <ol class="breadcrumb">
                        <li><a href='@Url.Content("~/Home/Index")'><i class="fa fa-dashboard"></i> Home</a></li>
                        <li><a href='@Url.Content("~/Home/Reports")'> Reports</a></li>
                        <li><a href='@Url.Content("~/Reports/CreditNoteProductCategory")'>Operational Reports</a></li>
                        <li class="active">Report</li>
                    </ol>
                </section>
            </div>
        </div>
        <div class="box-body">
            @using (Html.BeginForm("ViewCreditNoteProductCategory", "Reports", FormMethod.Post, new { id = "frm", name = "frm", enctype = "multipart/form-data" }))
            {
                <div class="row">
                    <div class="col-sm-4">
                        @{ Html.RenderPartial("ReportPagesLinks");}
                    </div>
                    <div class="col-sm-8">

                        <div class="row">
                            @if (ViewBag.Login == 10)
                            {
                                <div class="row" style="padding-bottom:10px;">
                                    <div class="rptTitle"> <h2>CreditNote Product Category</h2><br /></div>
                                    <div class="col-md-2">
                                        <label id="lblRegion" class="control-label">Region</label>
                                    </div>
                                    <div class="col-md-2">
                                        @Html.DropDownListFor(x => x.Branch, new SelectList(ViewBag.Branches, "Value", "Text"), "Select Branch", new { @class = "form-control input-sm" })
                                    </div>
                                </div>
                            }
                            <div class="row" style="padding-bottom:10px;">
                                <div class="col-md-2">
                                    <label id="lblRegion" class="control-label">Product Code</label>
                                </div>
                                <div class="col-md-2">
                                    @Html.DropDownListFor(x => x.ProductCode, new SelectList(ViewBag.productCategory, "Value", "Text"), null, new { @class = "form-control input-sm" })
                                </div>
                            </div>
                            <div class="row" style="padding-bottom:10px;">
                                <div class="col-md-2">
                                    <label id="lblRegion" class="control-label">From Month</label>
                                </div>
                                <div class="col-md-2 DtFrmTo">
                                    @Html.DropDownListFor(x => x.FromMonth, new SelectList(ViewBag.Months, "Value", "Text"), "Select Month", new { @class = "form-control input-sm" })
                                </div>
                            </div>
                            <div class="row" style="padding-bottom:10px;">
                                <div class="col-md-2">
                                    <label id="lblRegion" class="control-label">To Month</label>
                                </div>
                                <div class="col-md-2 DtFrmTo">
                                    @Html.DropDownListFor(x => x.ToMonth, new SelectList(ViewBag.Months, "Value", "Text"), "Select Month", new { @class = "form-control input-sm" })
                                </div>
                            </div>
                            <div class="row" style="padding-bottom:10px;">
                                <div class="col-md-2">
                                    <label id="lblRegion" class="control-label">Year</label>
                                </div>
                                <div class="col-md-2">
                                    @Html.DropDownListFor(x => x.Year, new SelectList(ViewBag.Year, "Value", "Text"), "Select Year", new { @class = "form-control input-sm" })
                                </div>
                                <div class="col-md-1">
                                    <button type="button" class="btn btn-sm btn-primary" data-toggle="modal" onclick="btnPrint()"><i class="fa fa-print"></i>Print</button>
                                    @*@Html.ActionLink("Print", "ViewCreditNoteProductCategory", "Reports", new { data_modal = "test", id = "btnViewReport", onclick = "btnPrint()", @class = "btn btn-sm btn-primary" })*@
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            }
        </div>
        <div class="box-footer">
            <div class="row">
                <div class="col-md-12">
                    <button class="btn btn-info btn-sm pull-right" type="button" onclick="location.href = '@Url.Content("~/Home/Reports")'"><i class="fa fa-backward"></i>&nbsp;Back</button>
                </div>
            </div>
        </div>
    </div>

    <script src="@Url.Content("~/Scripts/moment.js")"></script>
    <script src="@Url.Content("~/Scripts/bootstrap-datetimepicker.js")"></script>
    <script src="@Url.Content("~/Scripts/select2.min.js")"></script>
    <script type="text/javascript">
        $(function () {
            $('#Year').val('@Model.Year');
            $('#loader').hide();
            $('#CreditNoteProductCategory').parent().addClass('active');

            $('.datepicker').datetimepicker({
                useCurrent: false,
                format: 'DD/MM/YYYY',
                inline: false
            });
            $('#frm').validate({
                rules:
                    {
                        Branch: {
                            required: true
                        },
                        FromMonth: {
                            required: true
                        },
                        ToMonth: {
                            required: true
                        },
                        Year: {
                            required: true
                        },
                        ProductCode: {
                            required: true
                        }
                    }
            })
        });
        function btnPrint() {

            if ($('#frm').valid()) {
                var FromMonth = $("#FromMonth").val();
                var ToMonth = $("#ToMonth").val();
                var year = $('#Year').val();
                var productCode = $('#ProductCode').val();
                var ReportURL = ("RMACreditNote.ProductCategory.Quantity");
                var branchID = $('#Branch').val();

            @*var rooturl = '@Url.Action("ViewCreditNoteProductCategory", "Reports")';
            var url = rooturl + "?BranchID=" + branchID + "&FromMonth=" + FromMonth + "&ToMonth=" + ToMonth + "&Year=" + year + "&ProductCode=" + productCode + "&URL=" + ReportURL;
            $("#btnViewReport").attr("href", url);*@
                $.ajax({
                    url: '@Url.Content("~/Reports/ViewCreditNoteProductCategory?BranchID=")' + branchID + "&FromMonth=" + FromMonth + "&ToMonth=" + ToMonth + "&Year=" + year + "&ProductCode=" + productCode + "&URL=" + ReportURL,
                    method: 'get',
                    contentType: 'text/html',
                    success: function (html) {
                        $('#myModal').html(html);
                        $('#myModal').modal('show');
                    },
                    error: function (err) {
                    }
                });
            }
        }
    </script>
</section>

RMA.Web/Views/Reports/CreditNoteValue.cshtml
@model EZY.RMAS.Contract.RMACreditNoteDTO
@{
    ViewBag.Title = "CreditNoteValue";
}
<link href="@Url.Content("~/Css/datepicker3.css")" rel="stylesheet" />
<link href="@Url.Content("~/Css/select2.min.css")" rel="stylesheet" />

<div id="myModal" class="modal fade" role="dialog" data-backdrop="static" data-keyboard="false">
</div>
<div id="loader"></div>
<section class="content">
    <div class="box box-dnex">
        <div class="box-header with-border">
            <div class="row">
                <section class="content-header">
                    <ol class="breadcrumb">
                        <li><a href='@Url.Content("~/Home/Index")'><i class="fa fa-dashboard"></i> Home</a></li>
                        <li><a href='@Url.Content("~/Home/Reports")'> Reports</a></li>
                        <li><a href='@Url.Content("~/Reports/CreditNoteValue")'>Operational Reports</a></li>
                        <li class="active">Report</li>
                    </ol>
                </section>
            </div>
        </div>
        <div class="box-body">
            @using (Html.BeginForm("ViewCreditNoteValue", "Reports", FormMethod.Post, new { id = "frm", name = "frm", enctype = "multipart/form-data" }))
            {
                <div class="row">
                    <div class="col-sm-4">
                        @{ Html.RenderPartial("ReportPagesLinks");}
                    </div>
                    <div class="col-sm-8">
                        <div class="row">
                            @if (ViewBag.Login == 10)
                            {
                                <div class="row" style="padding-bottom:10px;">
                                    <div class="rptTitle"> <h2>CreditNote Value</h2><br /></div>
                                    <div class="col-md-2">
                                        <label id="lblRegion" class="control-label">Region</label>
                                    </div>
                                    <div class="col-md-2">
                                        @Html.DropDownListFor(x => x.Branch, new SelectList(ViewBag.Branches, "Value", "Text"), "Select Branch", new { @class = "form-control input-sm" })
                                    </div>
                                </div>
                            }
                            <div class="row" style="padding-bottom:10px;">
                                <div class="col-md-2">
                                    <label id="lblRegion" class="control-label">Product Code</label>
                                </div>
                                <div class="col-md-2">
                                    @Html.DropDownListFor(x => x.ProductCode, new SelectList(ViewBag.productCategory, "Value", "Text"), null, new { @class = "form-control input-sm" })
                                </div>
                            </div>
                            <div class="row" style="padding-bottom:10px;">
                                <div class="col-md-2">
                                    <label id="lblRegion" class="control-label">From Date</label>
                                </div>
                                <div class="col-md-2 DtFrmTo">
                                    @Html.DropDownListFor(x => x.FromMonth, new SelectList(ViewBag.Months, "Value", "Text"), "Select Month", new { @class = "form-control input-sm" })
                                </div>
                            </div>
                            <div class="row" style="padding-bottom:10px;">
                                <div class="col-md-2">
                                    <label id="lblRegion" class="control-label">To Date</label>
                                </div>
                                <div class="col-md-2 DtFrmTo">
                                    @Html.DropDownListFor(x => x.ToMonth, new SelectList(ViewBag.Months, "Value", "Text"), "Select Month", new { @class = "form-control input-sm" })
                                </div>
                            </div>
                            <div class="row" style="padding-bottom:10px;">
                                <div class="col-md-2">
                                    <label id="lblRegion" class="control-label">Year</label>
                                </div>
                                <div class="col-md-2">
                                    @Html.DropDownListFor(x => x.Year, new SelectList(ViewBag.Year, "Value", "Text"), "Select Year", new { @class = "form-control input-sm" })
                                </div>
                                <div class="col-md-1">
                                    <button type="button" class="btn btn-sm btn-primary" data-toggle="modal" onclick="btnPrint()"><i class="fa fa-print"></i>Print</button>
                                    @*@Html.ActionLink("Print", "ViewCreditNoteValue", "Reports", new { data_modal = "test", id = "btnViewReport", onclick = "btnPrint()", @class = "btn btn-sm btn-primary" })*@
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            }
        </div>
        <div class="box-footer">
            <div class="row">
                <div class="col-md-12">
                    <button class="btn btn-info btn-sm pull-right" type="button" onclick="location.href = '@Url.Content("~/Home/Reports")'"><i class="fa fa-backward"></i>&nbsp;Back</button>
                </div>

            </div>
        </div>
    </div>
    <script src="@Url.Content("~/Scripts/moment.js")"></script>
    <script src="@Url.Content("~/Scripts/bootstrap-datetimepicker.js")"></script>
    <script src="@Url.Content("~/Scripts/select2.min.js")"></script>

    <script type="text/javascript">
            $(function () {
                $('#Year').val('@Model.Year');
                $('#loader').hide();
				$('#CreditNoteValue').parent().addClass('active');

                $('.datepicker').datetimepicker({
                    useCurrent: false,
                    format: 'DD/MM/YYYY',
                    inline: false
                });
                $('#frm').validate({
                    rules:
                        {
                            Branch: {
                                required: true
                            },
                            FromMonth: {
                                required: true
                            },
                            ToMonth: {
                                required: true
                            },
                            Year: {
                                required: true
                            },
                            ProductCode:{
                                required:true
                            }
                        }
                })
            });
        function btnPrint() {

            if ($('#frm').valid()) {
                var FromMonth = $("#FromMonth").val();
                var ToMonth = $("#ToMonth").val();
                var year = $('#Year').val();
                var productCode = $('#ProductCode').val();
                var ReportURL = ("RMACreditNote.ProductCategory.Value");
                var branchID = $('#Branch').val();

                @*var rooturl = '@Url.Action("ViewCreditNoteValue", "Reports")';
				var url = rooturl + "?BranchID=" + branchID + "&FromMonth=" + FromMonth + "&ToMonth=" + ToMonth + "&Year=" + year + "&ProductCode=" + productCode + "&URL=" + ReportURL;
                $("#btnViewReport").attr("href", url);*@
                $.ajax({
                    url: '@Url.Content("~/Reports/ViewCreditNoteValue?BranchID=")' + branchID + "&FromMonth=" + FromMonth + "&ToMonth=" + ToMonth + "&Year=" + year + "&ProductCode=" + productCode + "&URL=" + ReportURL,
                    method: 'get',
                    contentType: 'text/html',
                    success: function (html) {
                        $('#myModal').html(html);
                        $('#myModal').modal('show');
                    },
                    error: function (err) {
                    }
                });
            }
        }
    </script>
</section>

RMA.Web/Views/Reports/ManagementReports.cshtml
@{
    ViewBag.Title = "ManagementReports";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section class="content">
    <div class="box box-default">
        <div class="box-header with-border">
            <div class="row">
                <section class="content-header">
                    <ol class="breadcrumb">
                        <li><a href='@Url.Content("~/Home/Index")'><i class="fa fa-dashboard"></i> Home</a></li>
                        @*<li><a href='@Url.Content("~/Home/Index")'>Modules</a></li>*@
                        <li><a href='@Url.Content("~/Home/Reports")'> Reports</a></li>
                        <li class="active">Management Reports</li>
                    </ol>
                </section>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                @{Html.RenderPartial("DashBoardsLinks");}
            </div>
        </div>
        <div class="box-footer">
            <div class="row">
                <div class="col-md-12">
                    <button class="btn btn-default btn-sm pull-right" type="button" onclick="location.href = '@Url.Content("~/Home/Reports")'"><i class="fa fa-backward"></i>&nbsp;Back</button>
                </div>

            </div>
        </div>
    </div>
</section>